development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:20ac1d1aa5a77ab5571b15623eb6c660@tarpon.redistogo.com:9748/
  channel_prefix: Opentok_production
